sudo: false
language: node_js
install: true
script: ./test/travis.sh
env:
  matrix:
  - NODE=6
  - NODE=5
  - NODE=4
  - BROWSER=chrome
  - BROWSER=firefox
  - BROWSER=safari
  - BROWSER=android
  - BROWSER=iphone
  global:
  - secure: ONS6y2R29uIn9pT9u0CvR+n94gTw5wpxLDfzrDq2zvMNJK0xlIXxNZfQgdg7dCVU+QHCf+eV2Z6exnC/ZCjQSo8PocZxZglyZ92aPNSrEaF6uSjsa9CMLf5oDoi85oHD8OpEQI+JDnoVN9wd0TOb9xIjZO3WMo5t9zgwO4c2cE5KunQvMXsN2tBtf6hJ7K9SQi8n83PwZfzAkDSH2gN8K0VyVd6RTWli+YODL1sgFhwH/pxDIrTrZ8CVe+Kfe18LdPQ5bGJ71iVWKX+KxcKnDLCZzP3+uC/4PTXVCndVKXvHmR0XZ+/lCApzA2ezIL9mXKtQrJlugg5WidHeaFawE6HCXdsulsyKQzMf4rMQDWbDIFouJWeIJSaipZFM3cqZNNaauiJ6TLR3gzVt96tAy/UR9GVl6jH1sDOBc5oNrvC0AQNB4JgEaB+lwuFdnVqf0obuMoiGRasOzN7eexQmciDCmmBso6qidDCwufvEYGhbGy9iMc9eDp2j2yJ8WB8e9s6xIi+zaDjGZSCBISadqS0LUc6HOK0QNihqQBEgOa9oej+d8gDMyUUQ+fiDbIitpO+cuU7MIw4hRIIWh2pCZZ/DQwT9fdAFHVnvXljBYHuR9V+uRXnUzhYWIONbSptjCL65p0dFLEtR4IZ2y34mXCRyDL7jKC8R+Z27LlWwFPQ=
  - secure: nqRqn00MFj8SYZxstdyid+lGM0OwVi0t0bVwCRX+QCpxZa3GSz9pgq4jO3VFN628kZNDEtb1l5Hja3rgy2PefBETESoP4MeGO6AEUwvMaMjVMG2nd8aCS/FJC5AcT/ljm4IC8iFRFKFr8CLVVovIsBu1LUnU5MlpR/MYxhVc4fgl00y2v7h2JEXgACdJt8ZJRCGQya2Ju/dmOOD22RS2fduhPuRV5zaAenn6or4UUm1aClSfTLe/ZIA3TO21iF0jVaR/Gl7sJCio1in6xg1hzJNIeoTeLF326ztyuGzedIMFe/6xWL4QH48NEOQ+LP+bcHVEsNjqK+7h1yKASyYIAOmeI7/BLO//iusXJLnc71IuF53l+P5TQkQBNEqyOYkBVnsxifHC96apExKo7WR7LuxdNZI+MNoOtlxSsFwDl+ei+Y39W7yRMrgszjopzufITta3tAbNWcH9lXJDa0IJLP44RjQWECmHuyq6K31Dj99YH+HaTphrwdfIj4fu5C+Qew9DPuiGoLjdLr0U2yH/GwGi8fmQ+HLU5ubswGLQpDlMOQ2TWDKFqV/fGc6aY1AAtoJACJkW+dIDbKYb+ARcO0LtWNUJ/r6c9NyDE4GmRCTD7LhMuugdbWvpE3vFZelaqQMvV8feEZ1MFcTYybsU3TyXJ2/fcENH6lmtlDA6umk=
notifications:
  email: false
